# created with the help of https://editor.swagger.io/

openapi: 3.0.1
info:
  title: Agnes UI
  version: 1.0.0
servers:
- url: /api
paths:
  /release:
    post:
      tags:
      - release
      summary: Add a new release
      operationId: add
      requestBody:
        description: The release to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Release'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
          
components:
  schemas:
    Release:
      type: object
      properties:
        commitish:
          type: string
        description:
          type: string
        name:
          type: string
