<?php
/**
 * InstanceApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  App
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Agnes UI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\Api;

/**
 * InstanceApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface InstanceApiInterface
{

    /**
     * Operation getAll
     *
     * gets all instances
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return App\Model\Instance[]
     *
     */
    public function getAll(&$responseCode, array &$responseHeaders);
}
