<?php
/**
 * ReleaseApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  App
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Agnes UI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Model\Release;

/**
 * ReleaseApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ReleaseApiInterface
{

    /**
     * Operation add
     *
     * Add a new release
     *
     * @param  App\Model\Release $release  The release to be created (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function add(Release $release, &$responseCode, array &$responseHeaders);
}
