// tslint:disable
/// <reference path="./custom.d.ts" />
/**
 * Agnes UI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    commitish?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    name?: string;
}

/**
 * ReleaseApi - axios parameter creator
 * @export
 */
export const ReleaseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new release
         * @param {Release} release The release to be created
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        add(release: Release, options: any = {}): RequestArgs {
            // verify required parameter 'release' is not null or undefined
            if (release === null || release === undefined) {
                throw new RequiredError('release','Required parameter release was null or undefined when calling add.');
            }
            const localVarPath = `/release`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (<any>"Release" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(release !== undefined ? release : {}) : (release || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReleaseApi - functional programming interface
 * @export
 */
export const ReleaseApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new release
         * @param {Release} release The release to be created
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        add(release: Release, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
            const localVarAxiosArgs = ReleaseApiAxiosParamCreator(configuration).add(release, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ReleaseApi - factory interface
 * @export
 */
export const ReleaseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Add a new release
         * @param {Release} release The release to be created
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        add(release: Release, options?: any) {
            return ReleaseApiFp(configuration).add(release, options)(axios, basePath);
        },
    };
};

/**
 * ReleaseApi - object-oriented interface
 * @export
 * @class ReleaseApi
 * @extends {BaseAPI}
 */
export class ReleaseApi extends BaseAPI {
    /**
     * 
     * @summary Add a new release
     * @param {Release} release The release to be created
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleaseApi
     */
    public add(release: Release, options?: any) {
        return ReleaseApiFp(this.configuration).add(release, options)(this.axios, this.basePath);
    }

}


