<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEj7QBe4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEj7QBe4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEj7QBe4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEj7QBe4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEj7QBe4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ej7QBe4',
    'container.build_id' => 'd4e80da7',
    'container.build_time' => 1565539750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEj7QBe4');
